filebeat.prospectors:
- input_type: log
  paths:
    - /var/log/app.log
  json.keys_under_root: true
  fields_under_root: true
  fields:
    environment: docker

output.logstash:
  hosts: ["fluent:5044"]
  index: docker.app

